# Generated by Django 5.2 on 2025-04-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_booking_app', '0006_alter_reservation_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone',
        ),
    ]
